Added Category and endpoints for them
IhorTrokhymchuk/store pull request #10
Opened 2024-02-03 18:24 UTC by IhorTrokhymchuk

2024-02-04 13:25 UTC, okuzan requested changes

2024-02-04 13:25 UTC, okuzan commented on src/main/java/com/example/store/model/Category.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE categories SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```
true and false are sql keywords too

2024-02-04 13:25 UTC, okuzan commented on src/main/java/com/example/store/model/User.java
> +@SQLDelete(sql = "UPDATE users SET is_deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE users SET is_deleted = TRUE WHERE id = ?")
```

2024-02-04 13:25 UTC, okuzan commented on src/main/java/com/example/store/controller/CategoryController.java
> +@RequestMapping(value = "/category")
```suggestion
@RequestMapping(value = "/categories")
```

2024-02-04 13:25 UTC, okuzan commented on src/main/java/com/example/store/repository/book/BookRepository.java
> +    List<Book> findAllByCategoriesId(Long id, Pageable pageable);
```suggestion
    List<Book> findAllByCategoryId(Long id, Pageable pageable);
```

2024-02-04 13:25 UTC, okuzan commented on src/main/resources/db/changelog/changes/create-books_categories-table.yaml
> +            constraintName: FK_books_categories_categories
```suggestion
            constraintName: FK_books_categories_categories
            
```

2024-02-04 13:25 UTC, okuzan commented on src/main/java/com/example/store/service/impl/CategoryServiceImpl.java
> +        );
let's create
private Category getCategoryById(Long id) {
    return categoryRepository.findById(id)
            .orElseThrow(() -> new EntityNotFoundException("Can't find category by id: " + id));
}

2024-02-04 13:25 UTC, okuzan commented on src/main/java/com/example/store/service/impl/CategoryServiceImpl.java
> +            throw new EntityNotFoundException("Can't find category in db");
include id in the message

2024-02-05 14:03 UTC, olekskov approved these changes

2024-02-05 14:55 UTC, merged