Added tests for Book and Categories
IhorTrokhymchuk/store pull request #14
Opened 2024-02-23 16:08 UTC by IhorTrokhymchuk

2024-02-26 15:41 UTC, IhorTrokhymchuk commented
<img width="614" alt="Screenshot 2024-02-26 at 17 26 01" src="https://github.com/IhorTrokhymchuk/store/assets/134588724/71ac6e62-d0a2-455f-99e3-16bb089837b1">
<img width="614" alt="Screenshot 2024-02-26 at 17 27 41" src="https://github.com/IhorTrokhymchuk/store/assets/134588724/1d7c20e4-e8b9-4dec-ad81-9cf267cc6ac3">

2024-02-27 14:00 UTC, okuzan requested changes
GJ overall

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/controller/CategoryControllerTest.java
> +                            "database/books/add-books-with-any-categories-to-book-table.sql"));
better extract to constants

2024-02-27 14:00 UTC, okuzan commented on src/test/resources/database/delete-all-data.sql
> +delete from categories;
```suggestion
delete from categories;

```

2024-02-27 14:00 UTC, okuzan commented on src/test/resources/application.properties
> +
```suggestion
```

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/service/CategoryServiceTest.java
> +        assertThrows(EntityNotFoundException.class, () -> categoryService.findAll(pageable));
it's normal for queries like findAll to not return anything, we shouldn't throw exception in this case

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/service/CategoryServiceTest.java
> +        Long testCategoryId = Long.MAX_VALUE;
a simple negative value would be more obvious, Long.MAX_VALUE technically could be a valid id

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/service/CategoryServiceTest.java
> +    void getBooksByCategory_GetExistData_ShouldReturnListBookDto() {
use `existent` `nonexistent` for more clarity

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/service/CategoryServiceTest.java
> +                    categoryDto.setDescription(category.getDescription());
looks like a repeated logic that could be extract to a private method

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/service/BookServiceTest.java
> +                }
it's huge, extract to a private method

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/controller/CategoryControllerTest.java
> +    @DisplayName("Delete category by id with out authorities")
some of your display names start from lowercase, some from uppercase

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/controller/BookControllerTest.java
> +        requestDto.setPrice(testPrice);
test data setup takes a lot of lines, encapsulate it in a private method everywhere

2024-02-27 14:00 UTC, okuzan commented on src/test/java/com/example/store/controller/BookControllerTest.java
> +class BookControllerTest {
include Integration in name for clarity

2024-02-27 19:30 UTC, okuzan approved these changes
LGTM

2024-02-27 20:29 UTC, merged